### ISSUE TITLE
META: complete transition to this repo being source-of-truth

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-integration-rabbitmq#3]
This repository will be the source-of-truth for rabbitmq-related logstash plugins, but there are some loose threads that need to be tied up to ensure users and contributors have a clear path to reporting and fixing bugs, requesting features, etc.

 - [ ] ensure outside contributors (e.g., those who are not members of the `logstash-plugins` org), if any, have equivalent permissions on this repository
 - [ ] update origin plugins to point to this repository in `README.md`, `.github/*`
   - [ ] logstash-input-rabbitmq
   - [ ] logstash-output-rabbitmq
 - [ ] migrate existing issues
 - [ ] migrate in-flight pull-requests
 - [ ] absorb upstream contributions
    - [ ] https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/121

**Comment by jsvd** [comment]
>  migrate existing issues

Regarding this, there's no github api to perform issue transferring, we can only script the closing and creating of a new issue with the old one's content.
Another alternative to this is to add a comment to each of the opened issues.
It could be something along the lines of "this repository as migrated to <url>, if this issue is important to you please add a comment here and we'll transfer it, since GitHub doesn't have a transfer issue API".

>  migrate in-flight pull-requests

on the same vein as the comment about issues, we can't migrate them automatically, with the added difficulty that prs won't apply anymore to the destination repository.

>  absorb upstream contributions

maybe we can provide as script that shows the list of commits that haven't been included in the integration repository.

>  update origin plugins to point to this repository in README.md, .github/*

Maybe @karenzone can help here on where (if anywhere) we should make it clear that the plugin lives in a new repository.


Also, will there be a timeframe for archiving the repository?
